### ISSUE TITLE
Hours and minutes

### ISSUE THREAD

**Issue by richsdixon** [ksgwxfan/hurdat2parser#2]
Hi there

Really handy piece of code. I noticed that when you output the hours and minutes columns I was getting an offset by one row - I had a tinker and I think
```
    Hours_in_UTC=int(data[1][0:2])
    Minutes_in_UTC=int(data[1][2:4])
```
should be 
```
    Hours_in_UTC=int(data[1][0:3])
    Minutes_in_UTC=int(data[1][3:5])
```
...or at least gives me the right results 

See what you think. Have pasted below a screenshot of the original code and then the results of my edit...

![issue](https://github.com/ksgwxfan/hurdat2parser/assets/73081663/2e6abb61-1203-472b-81f9-8c944e21d1b5)
![edit](https://github.com/ksgwxfan/hurdat2parser/assets/73081663/6814ce57-d646-4abc-b5a0-c6c01131cfb3)

**Comment by ksgwxfan** [comment]
Thanks for your comment.

Is this code from the `output_storms_csv()` method?

It's probably been a while since I spent time working on this method but I looked at the output earlier and I don't see where these fields are included or the piece of code you mentioned. I'll have more time this evening to investigate.

But when you have time, please provide me:
- version of the module (I think it is accessible via `help(hurdat2psrser)`)
- file, method, and line # (if you can access that) where that code is found.

I want to reproduce the issue if possible. 

Thanks in advance!

**EDIT (2024-05-24 1715z)** _Oh, is this output from a GIS file (shapefile or geojson)? I'll check this too_
**EDIT (2024-05-25 1000z)** _Where did you find this code? I didn't get any search result when searching the repo._

**Comment by ksgwxfan** [comment]
Hello. Can you direct me to where you found this code fragment? I can't seem to find it in my repo. Please see my post above and answer the questions the best you can. Thanks in advance.

**Comment by richsdixon** [comment]
Hi there

Sorry for delay in reply, it's a holiday long weekend in the UK.

I can't actually find where in your code the issue was! I've shown the 
chunk of code below (it has my edit / directories in there):

Richard

"""

# Best Track Data (HURDAT2)

Atlantic hurricane database (HURDAT2) 1851-2018 (5.9MB download)
This dataset was provided on 10 May 2019 to include the 2018 update to 
the best tracks.

This dataset (known as Atlantic HURDAT2) has a comma-delimited, text 
format with six-hourly information on the location, maximum winds, 
central pressure, and (beginning in 2004) size of all known tropical 
cyclones and subtropical cyclones. The original HURDAT database has been 
retired.

Detailed information regarding the Atlantic Hurricane Database 
Re-analysis Project is available from the Hurricane Research Division.

ref:https://www.nhc.noaa.gov/data/

#https://www.nhc.noaa.gov/data/hurdat/hurdat2-format-atlantic.pdf
# HURDAT2 Processor

This is a python script that convert your HURDAT to a dataframe and 
generate a CSV file for you to eaily process this data. This work is 
part of trajectory segmentation research[1]. We use this dataset for 
evaluation purposes. If you are going to apply this script please cite 
to our work.
Thanks.
[1]: Etemad, Mohammad, et al. "A Trajectory Segmentation Algorithm Based 
on Interpolation-based Change Detection Strategies." EDBT/ICDT 
Workshops. 2019.

"""
importpandasaspd
Record_identifier_dic={'C':"Closest approach to a coast, not followed by 
a landfall"
,'G':"Genesis"
,'I':"An intensity peak in terms of both pressure and wind"
,'L':"Landfall (center of system crossing a coastline)"
,'P':"Minimum in central pressure"
,'R':"Provides additional detail on the intensity of the cyclone when 
rapid changes are underway"
,'S':"Change of status of the system"
,'T':"Provides additional detail on the track (position) of the cyclone"
,'W':"Maximum sustained wind speed"}
Status_of_system_dic={
'TD':"Tropical cyclone of tropical depression intensity (< 34 knots)"
,'TS':"Tropical cyclone of tropical storm intensity (34-63 knots)"
,'HU':"Tropical cyclone of hurricane intensity (> 64 knots)"
,'EX':"Extratropical cyclone (of any intensity)"
,'SD':"Subtropical cyclone of subtropical depression intensity (< 34 
knots)"
,'SS':"Subtropical cyclone of subtropical storm intensity (> 34 knots)"
,'LO':"A low that is neither a tropical cyclone, a subtropical cyclone, 
nor an extratropical cyclone (of any intensity)"
,'WV':"Tropical Wave (of any intensity)"
,'DB':"Disturbance (of any intensity)"}


pd.set_option('display.max_columns', None)

defprocess_details(data):
     data=data.split(',')
     Year=int(data[0][0:4])
     Month=int(data[0][4:6])
     Day=int(data[0][6:8])
     Hours_in_UTC=int(data[1][0:3])
     Minutes_in_UTC=int(data[1][3:5])
     Record_identifier=data[2].strip()
     try:
         Record_identifier_desc=Record_identifier_dic[data[2].strip()]
     except:
         Record_identifier_desc=None

     Status_of_system=data[3].strip()
     try:
         Status_of_system_desc=Status_of_system_dic[Status_of_system]
     except:
         Status_of_system_desc=None

     ifdata[4].strip()[-1:] in ('N','S'):
         ifdata[4].strip()[-1:]=='N':
             Latitude=float(data[4].strip()[:-1])
         else:
             Latitude=-1.0*float(data[4].strip()[:-1])
     else:
         Latitude=-999

     ifdata[5].strip()[-1:] in ('E','W'):
         ifdata[5].strip()[-1:]=='E':
             Longitude=float(data[5].strip()[:-1])
         else:
             Longitude=-1.0*float(data[5].strip()[:-1])
     else:
         Longitude=-999
     Maximum_sustained_wind_in_knots=float(data[6].strip())
     Minimum_Pressure_in_millibars=float(data[7].strip())
     i=8
     F34_kt_wind_radii_maximum_northeastern=float(data[i].strip())
     i+=1
     F34_kt_wind_radii_maximum_southeastern=float(data[i].strip())
     i+=1
     F34_kt_wind_radii_maximum_southwestern=float(data[i].strip())
     i+=1
     F34_kt_wind_radii_maximum_northwestern=float(data[i].strip())


     i+=1
     F50_kt_wind_radii_maximum_northeastern=float(data[i].strip())
     i+=1
     F50_kt_wind_radii_maximum_southeastern=float(data[i].strip())
     i+=1
     F50_kt_wind_radii_maximum_southwestern=float(data[i].strip())
     i+=1
     F50_kt_wind_radii_maximum_northwestern=float(data[i].strip())

     i+=1
     F64_kt_wind_radii_maximum_northeastern=float(data[i].strip())
     i+=1
     F64_kt_wind_radii_maximum_southeastern=float(data[i].strip())
     i+=1
     F64_kt_wind_radii_maximum_southwestern=float(data[i].strip())
     i+=1
     F64_kt_wind_radii_maximum_northwestern=float(data[i].strip())



     
res=Year,Month,Day,Hours_in_UTC,Minutes_in_UTC,Record_identifier,Record_identifier_desc,Status_of_system,Status_of_system_desc,Latitude,Longitude,Maximum_sustained_wind_in_knots,Minimum_Pressure_in_millibars,F34_kt_wind_radii_maximum_northeastern,F34_kt_wind_radii_maximum_southeastern,F34_kt_wind_radii_maximum_southwestern,F34_kt_wind_radii_maximum_northwestern,F50_kt_wind_radii_maximum_northeastern,F50_kt_wind_radii_maximum_southeastern,F50_kt_wind_radii_maximum_southwestern,F50_kt_wind_radii_maximum_northwestern,F64_kt_wind_radii_maximum_northeastern,F64_kt_wind_radii_maximum_southeastern,F64_kt_wind_radii_maximum_southwestern,F64_kt_wind_radii_maximum_northwestern
     returnres

defprocess_header(data):
     data=data.split(',')
     
Basin,ATCF_cyclone_number_for_that_year,Year,Name,Number_of_best_track_entries=data[0][0:2],data[0][2:4],data[0][4:8],data[1].strip(),data[2].strip()
     
res=Basin,ATCF_cyclone_number_for_that_year,Year,Name,Number_of_best_track_entries
     returnres


defidentify_line_type(data):
#    print(data.split(','))
     iflen(data.split(','))>4:
         return2
     else:
         return1
defcolumns_name():
     res=['Basin','ATCF_cyclone_number_for_that_year','Year_','Name',
          #'Number_of_best_track_entries',
          'Year','Month','Day','Hours_in_UTC','Minutes_in_UTC',
          
'Record_identifier','Record_identifier_desc','Status_of_system','Status_of_system_desc','Latitude','Longitude'
          
,'Maximum_sustained_wind_in_knots','Minimum_Pressure_in_millibars','F34_kt_wind_radii_maximum_northeastern',
          
'F34_kt_wind_radii_maximum_southeastern','F34_kt_wind_radii_maximum_southwestern',
          
'F34_kt_wind_radii_maximum_northwestern','F50_kt_wind_radii_maximum_northeastern',
          
'F50_kt_wind_radii_maximum_southeastern','F50_kt_wind_radii_maximum_southwestern',
          
'F50_kt_wind_radii_maximum_northwestern','F64_kt_wind_radii_maximum_northeastern',
          
'F64_kt_wind_radii_maximum_southeastern','F64_kt_wind_radii_maximum_southwestern',
          'F64_kt_wind_radii_maximum_northwestern']
     returnres

pf=[]
header_fields=[]
filepath=r'C:\Users\richs\Dropbox\Work\Research\USHU\HURDAT2\hurdat2-1851-2023-051124.txt'
withopen(filepath) asfp:
     ln=fp.readline()
     whileln:

         lt=identify_line_type(ln)

         details=[]
         if (lt==1):
             header_fields=process_header(ln)
             details=[]
         else:
             details=process_details(ln)
         if (details!=[]):
             n=list(header_fields[:-1])+list(details)

             pf.append(n)
         ln=fp.readline()

df=pd.DataFrame(pf)

#df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)



df.columns=columns_name()

df['Date'] =pd.to_datetime(dict(year=df['Year'],
                                  month=df['Month'],
                                  day=df['Day']))



df['dayofyear'] =df['Date'].dt.dayofyear

test=df[['dayofyear','Maximum_sustained_wind_in_knots']].copy()


# Assuming your DataFrame is called 'df'
#min_dayofyear = 
df.groupby('Maximum_sustained_wind_in_knots').apply(lambda x: 
x.loc[x['Maximum_sustained_wind_in_knots'] > 
x['Maximum_sustained_wind_in_knots'].min(), 'dayofyear'].idxmin())

#min_dayofyear = 
df.groupby('Maximum_sustained_wind_in_knots')['dayofyear'].idxmin()
#new_df = df.loc[min_dayofyear].reset_index()


df90=df[df['dayofyear']>90]

test=df90.groupby('Maximum_sustained_wind_in_knots')['dayofyear'].min()

df.to_csv(r'C:\Users\richs\Dropbox\Work\Research\USHU\HURDAT2\hurdat2_240524.csv')
test.to_csv(r'C:\Users\richs\Dropbox\Work\Research\USHU\HURDAT2\test.csv')



Richard Dixon PhD
Director, CatInsight
Visiting Research Fellow, Department of Meteorology, University of 
Reading

***@***.*** | www.catinsight.co.uk
+447866159983 | @catinsight


------ Original Message ------
From "Kyle Gentry" ***@***.***>
To "ksgwxfan/hurdat2parser" ***@***.***>
Cc "richsdixon" ***@***.***>; "Author" 
***@***.***>
Date 27/05/2024 07:15:44
Subject Re: [ksgwxfan/hurdat2parser] Hours and minutes (Issue #2)

**Comment by ksgwxfan** [comment]
Hi, it appears you may have found it from here: [https://github.com/metemaad/HURDAT2_processor/blob/master/HURDAT2_processor.py](https://github.com/metemaad/HURDAT2_processor/blob/master/HURDAT2_processor.py).

The `output_storms_csv()` method in my module may yield similar results to what you're working with above. It doesn't have Genesis or Decay fields, just duration.

If you have a project you're working on but you're not sure if my module will work for you, feel free to submit a new "issue" with the "how to" designation.
